# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXqDcj-uzyG7ybjIP5ug-D5t8EyXoYsS
"""

import tensorflow as tf

path = tf.keras.utils.get_file(
    'shakespeare.txt',
    'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt'
)

with open(path, 'r') as f:
    text = f.read()

print("Total characters:", len(text))
print(text[:300])

!pip install tensorflow numpy matplotlib

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import random
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# STEP 1: LOAD DATASET (Shakespeare - Auto Download)
# ============================================================
print("STEP 1: Loading Dataset")

path = tf.keras.utils.get_file(
    'shakespeare.txt',
    'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt'
)

with open(path, 'r') as f:
    text = f.read()

# Use a smaller portion to train faster
text = text[:200000]

print("Total characters:", len(text))
print("Sample text:\n", text[:300])

# ============================================================
# STEP 2: PREPARE CHARACTER MAPPINGS
# ============================================================
print("\nSTEP 2: Preparing Character Mappings")

chars      = sorted(list(set(text)))
vocab_size = len(chars)

print("Total unique characters:", vocab_size)

char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for i, ch in enumerate(chars)}

print("Mapping done!")

# ============================================================
# STEP 3: CREATE SEQUENCES
# ============================================================
print("\nSTEP 3: Creating Sequences")

SEQ_LENGTH = 100
STEP       = 3

sequences  = []
next_chars = []

for i in range(0, len(text) - SEQ_LENGTH, STEP):
    sequences.append(text[i: i + SEQ_LENGTH])
    next_chars.append(text[i + SEQ_LENGTH])

print("Total sequences:", len(sequences))

# ============================================================
# STEP 4: VECTORIZE
# ============================================================
print("\nSTEP 4: Vectorizing...")

X = np.zeros((len(sequences), SEQ_LENGTH, vocab_size), dtype=np.bool_)
y = np.zeros((len(sequences), vocab_size), dtype=np.bool_)

for i, seq in enumerate(sequences):
    for t, char in enumerate(seq):
        X[i, t, char_to_idx[char]] = 1
    y[i, char_to_idx[next_chars[i]]] = 1

print("X shape:", X.shape)
print("y shape:", y.shape)

# ============================================================
# STEP 5: BUILD MODEL
# ============================================================
print("\nSTEP 5: Building LSTM Model")

model = Sequential([
    LSTM(128, input_shape=(SEQ_LENGTH, vocab_size)),
    Dense(vocab_size, activation='softmax')
])

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam'
)

model.summary()

# ============================================================
# STEP 6: HELPER FUNCTION
# ============================================================
def sample(preds, temperature=1.0):
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds + 1e-10) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    return np.argmax(np.random.multinomial(1, preds, 1))

def generate_text(seed_text, length=300, temperature=0.5):
    generated = seed_text
    for _ in range(length):
        x_pred = np.zeros((1, SEQ_LENGTH, vocab_size))
        for t, char in enumerate(seed_text):
            if char in char_to_idx:
                x_pred[0, t, char_to_idx[char]] = 1
        preds     = model.predict(x_pred, verbose=0)[0]
        next_idx  = sample(preds, temperature=temperature)
        next_char = idx_to_char[next_idx]
        generated += next_char
        seed_text  = seed_text[1:] + next_char
    return generated[SEQ_LENGTH:]

# ============================================================
# STEP 7: TRAIN MODEL
# ============================================================
print("\nSTEP 6: Training Model...")

class TextGenerator(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % 5 == 0:
            print("\n--- Text after epoch", epoch + 1, "---")
            start_idx = random.randint(0, len(text) - SEQ_LENGTH - 1)
            seed      = text[start_idx: start_idx + SEQ_LENGTH]
            result    = generate_text(seed, length=200, temperature=0.5)
            print(result)
            print("-" * 50)

history = model.fit(
    X, y,
    batch_size=128,
    epochs=30,
    callbacks=[
        EarlyStopping(monitor='loss', patience=5, restore_best_weights=True),
        TextGenerator()
    ]
)

# ============================================================
# STEP 8: PLOT TRAINING LOSS
# ============================================================
print("\nSTEP 7: Training Loss")

plt.figure(figsize=(8, 5))
plt.plot(history.history['loss'], color='steelblue', linewidth=2)
plt.title('Model Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)
plt.tight_layout()
plt.show()

# ============================================================
# STEP 9: GENERATE TEXT
# ============================================================
print("\nSTEP 8: Generating Text with Different Temperatures")

start_idx = random.randint(0, len(text) - SEQ_LENGTH - 1)
seed      = text[start_idx: start_idx + SEQ_LENGTH]

print("\nSEED TEXT:")
print(seed)
print("=" * 50)

for temp in [0.3, 0.5, 0.8]:
    print("\nTemperature:", temp)
    print("-" * 50)
    result = generate_text(seed, length=300, temperature=temp)
    print(result)
    print("-" * 50)

# ============================================================
# STEP 10: SAVE MODEL
# ============================================================
print("\nSTEP 9: Saving Model")
model.save('/content/rnn_text_model.h5')
print("Model saved!")

print("\nALL DONE! Character-level RNN Text Generation complete.")