# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNBo7KjthfvLRogjPzk3PA7TQjUU0n75
"""

!pip install nltk scikit-learn pandas numpy matplotlib seaborn
from google.colab import files
uploaded = files.upload()

import os
print(os.listdir('/content'))

'/content/train_data.txt',

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

import nltk
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# ============================================================
# STEP 1: LOAD DATASET
# ============================================================
print("STEP 1: Loading Dataset")

df = pd.read_csv(
    '/content/train_data.txt',
    sep=':::',
    engine='python',
    header=None,
    names=['ID', 'TITLE', 'GENRE', 'DESCRIPTION']
)

print("Dataset Shape:", df.shape)
print(df.head())

# ============================================================
# STEP 2: EDA
# ============================================================
print("\nSTEP 2: Genre Distribution")
print(df['GENRE'].value_counts())

plt.figure(figsize=(12, 5))
df['GENRE'].value_counts().plot(kind='bar', color='steelblue', edgecolor='black')
plt.title('Genre Distribution')
plt.xlabel('Genre')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# ============================================================
# STEP 3: TEXT PREPROCESSING
# ============================================================
print("\nSTEP 3: Preprocessing Text...")

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words and len(w) > 2]
    return ' '.join(tokens)

df['CLEAN_DESC'] = df['DESCRIPTION'].apply(preprocess_text)
print("Preprocessing done!")

# ============================================================
# STEP 4: LABEL ENCODING
# ============================================================
print("\nSTEP 4: Encoding Labels")
le = LabelEncoder()
df['GENRE_ENCODED'] = le.fit_transform(df['GENRE'])
print("Genres:", list(le.classes_))

# ============================================================
# STEP 5: TRAIN TEST SPLIT
# ============================================================
print("\nSTEP 5: Splitting Data")
X = df['CLEAN_DESC']
y = df['GENRE_ENCODED']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print("Train size:", len(X_train))
print("Test size:", len(X_test))

# ============================================================
# STEP 6: TF-IDF VECTORIZATION
# ============================================================
print("\nSTEP 6: TF-IDF Vectorization")
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1, 2), sublinear_tf=True)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)
print("Vectorization done!")

# ============================================================
# STEP 7: TRAIN MODELS
# ============================================================
print("\nSTEP 7: Training Models...")

models = {
    "Naive Bayes": MultinomialNB(alpha=0.1),
    "Logistic Regression": LogisticRegression(max_iter=1000, C=5, random_state=42),
    "Linear SVM": LinearSVC(C=1.0, max_iter=2000, random_state=42)
}

results = {}

for name, model in models.items():
    print("\nTraining:", name)
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)
    acc = accuracy_score(y_test, y_pred)
    results[name] = {'model': model, 'predictions': y_pred, 'accuracy': acc}
    print("Accuracy:", round(acc * 100, 2), "%")
    print(classification_report(y_test, y_pred, target_names=le.classes_))

# ============================================================
# STEP 8: MODEL COMPARISON CHART
# ============================================================
print("\nSTEP 8: Model Comparison")
model_names = list(results.keys())
accuracies = [results[m]['accuracy'] * 100 for m in model_names]

plt.figure(figsize=(8, 5))
bars = plt.bar(model_names, accuracies, color=['#4C72B0', '#DD8452', '#55A868'], edgecolor='black')
plt.ylim(0, 100)
plt.ylabel('Accuracy (%)')
plt.title('Model Accuracy Comparison')
for bar, acc in zip(bars, accuracies):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1, str(round(acc, 2)) + '%', ha='center')
plt.tight_layout()
plt.show()

# ============================================================
# STEP 9: CONFUSION MATRIX
# ============================================================
print("\nSTEP 9: Confusion Matrix")
best_model_name = max(results, key=lambda m: results[m]['accuracy'])
best_preds = results[best_model_name]['predictions']

acc = results[best_model_name]['accuracy'] * 100
print("Best Model:", best_model_name, "| Accuracy:", round(acc, 2), "%")

cm = confusion_matrix(y_test, best_preds)
plt.figure(figsize=(14, 10))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
disp.plot(xticks_rotation=45, cmap='Blues', ax=plt.gca())
plt.title('Confusion Matrix - ' + best_model_name, fontsize=13)
plt.tight_layout()
plt.show()

# ============================================================
# STEP 10: PREDICT NEW TEXT
# ============================================================
print("\nSTEP 10: Predicting New Examples")

def predict_genre(plot_summary):
    model = results[best_model_name]['model']
    cleaned = preprocess_text(plot_summary)
    vectorized = tfidf.transform([cleaned])
    pred = model.predict(vectorized)
    genre = le.inverse_transform(pred)[0]
    return genre

examples = [
    "A spaceship crew battles alien creatures on a distant planet to survive.",
    "Two people fall in love during a summer in Paris.",
    "A detective investigates a series of mysterious murders in the city.",
    "A group of friends go on a hilarious road trip across America.",
]

for text in examples:
    genre = predict_genre(text)
    print("Plot :", text[:60])
    print("Genre:", genre)
    print()

print("ALL DONE! Movie Genre Classification complete.")
