# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-hZkY2YmyeHmVYNYemcasG9043ec8Cv
"""

!pip install nltk scikit-learn pandas numpy matplotlib seaborn

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)

import nltk
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# ============================================================
# STEP 1: LOAD DATASET
# ============================================================
print("STEP 1: Loading Dataset")

df = pd.read_csv('/content/spam.csv', encoding='latin-1')

# Keep only relevant columns
df = df[['v1', 'v2']]
df.columns = ['Label', 'Message']

print("Dataset Shape:", df.shape)
print(df.head())

# ============================================================
# STEP 2: EDA
# ============================================================
print("\nSTEP 2: Exploratory Data Analysis")

print("Label Distribution:")
print(df['Label'].value_counts())
print("Spam %:", round(df['Label'].value_counts()['spam'] / len(df) * 100, 2), "%")

# Plot label distribution
plt.figure(figsize=(6, 4))
df['Label'].value_counts().plot(kind='bar', color=['steelblue', 'red'], edgecolor='black')
plt.title('Spam vs Ham Distribution')
plt.xlabel('Label')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Message length analysis
df['Message_Length'] = df['Message'].apply(len)

plt.figure(figsize=(10, 4))
df[df['Label'] == 'ham']['Message_Length'].plot(
    kind='hist', bins=50, alpha=0.7, label='Ham', color='steelblue')
df[df['Label'] == 'spam']['Message_Length'].plot(
    kind='hist', bins=50, alpha=0.7, label='Spam', color='red')
plt.title('Message Length Distribution')
plt.xlabel('Message Length')
plt.ylabel('Count')
plt.legend()
plt.tight_layout()
plt.show()

# ============================================================
# STEP 3: TEXT PREPROCESSING
# ============================================================
print("\nSTEP 3: Preprocessing Text...")

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(w) for w in tokens
              if w not in stop_words and len(w) > 2]
    return ' '.join(tokens)

df['Clean_Message'] = df['Message'].apply(preprocess_text)

print("Sample original :", df['Message'].iloc[0])
print("Sample cleaned  :", df['Clean_Message'].iloc[0])
print("Preprocessing done!")

# ============================================================
# STEP 4: LABEL ENCODING
# ============================================================
print("\nSTEP 4: Encoding Labels")

le = LabelEncoder()
df['Label_Encoded'] = le.fit_transform(df['Label'])

print("Labels:", list(le.classes_))
print("ham=0, spam=1")

# ============================================================
# STEP 5: TRAIN TEST SPLIT
# ============================================================
print("\nSTEP 5: Train Test Split")

X = df['Clean_Message']
y = df['Label_Encoded']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train size:", len(X_train))
print("Test size :", len(X_test))

# ============================================================
# STEP 6: TF-IDF VECTORIZATION
# ============================================================
print("\nSTEP 6: TF-IDF Vectorization")

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

print("Vectorization done!")
print("Matrix shape:", X_train_tfidf.shape)

# ============================================================
# STEP 7: TRAIN MODELS
# ============================================================
print("\nSTEP 7: Training Models...")

models = {
    "Naive Bayes"        : MultinomialNB(alpha=0.1),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Linear SVM"         : LinearSVC(C=1.0, max_iter=2000, random_state=42)
}

results = {}

for name, model in models.items():
    print("\nTraining:", name)
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)
    acc    = accuracy_score(y_test, y_pred)
    results[name] = {
        'model'      : model,
        'predictions': y_pred,
        'accuracy'   : acc
    }
    print("Accuracy:", round(acc * 100, 2), "%")
    print(classification_report(y_test, y_pred, target_names=['Ham', 'Spam']))

# ============================================================
# STEP 8: MODEL COMPARISON CHART
# ============================================================
print("\nSTEP 8: Model Comparison")

model_names = list(results.keys())
accuracies  = [results[m]['accuracy'] * 100 for m in model_names]

plt.figure(figsize=(8, 5))
bars = plt.bar(model_names, accuracies,
               color=['#4C72B0', '#DD8452', '#55A868'], edgecolor='black')
plt.ylim(0, 110)
plt.ylabel('Accuracy (%)')
plt.title('Model Accuracy Comparison')
for bar, acc in zip(bars, accuracies):
    plt.text(bar.get_x() + bar.get_width() / 2,
             bar.get_height() + 1,
             str(round(acc, 2)) + '%', ha='center', fontsize=11)
plt.tight_layout()
plt.show()

# ============================================================
# STEP 9: CONFUSION MATRIX FOR BEST MODEL
# ============================================================
print("\nSTEP 9: Confusion Matrix")

best_model_name = max(results, key=lambda m: results[m]['accuracy'])
best_preds      = results[best_model_name]['predictions']

print("Best Model:", best_model_name)
print("Accuracy  :", round(results[best_model_name]['accuracy'] * 100, 2), "%")

cm = confusion_matrix(y_test, best_preds)
plt.figure(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Ham', 'Spam'])
disp.plot(cmap='Blues', ax=plt.gca())
plt.title('Confusion Matrix - ' + best_model_name)
plt.tight_layout()
plt.show()

# ============================================================
# STEP 10: PREDICT NEW MESSAGES
# ============================================================
print("\nSTEP 10: Predicting New Messages")

best_model = results[best_model_name]['model']

def predict_spam(message):
    cleaned   = preprocess_text(message)
    vectorized = tfidf.transform([cleaned])
    pred      = best_model.predict(vectorized)[0]
    label     = le.inverse_transform([pred])[0]
    return label.upper()

# Example messages
examples = [
    "Congratulations! You have won a FREE iPhone. Click here to claim now!",
    "Hey, are we still meeting for lunch tomorrow?",
    "URGENT: Your bank account has been suspended. Call now to verify.",
    "Can you please send me the notes from today's class?",
    "Win cash prizes worth $1000! Reply WIN to this number now!",
    "Mom, I will be home late today. Don't wait for dinner."
]

print("\n" + "-" * 55)
for msg in examples:
    result = predict_spam(msg)
    print("Message :", msg[:55])
    print("Predicted:", result)
    print("-" * 55)

print("\nALL DONE! Spam SMS Detection complete.")
